### ISSUE TITLE
Tomte never closes finishes installing fixes.

### ISSUE THREAD

**Issue by hfinger** [tuxedocomputers/tuxedo-tomte#24]
Tomte is showing a Gnome Notification:
```
TUXEDO Tomte is installing fixes
Please do not restart or shutdown the system
```

The notification cannot be closed. It just stays there forever on top of everything. As it suggests that the laptop should not be restarted or shutdown there is NO way to get rid of that annoying message.
That is really bad UX. Did nobody think about that?
No indication whatsoever what is going on. Should I wait for months or years until that gnome notification disappears? I would really like to fix it by restarting the system, but oops, I shouldn't?

**Comment by tuxedo-ma** [comment]
Hi @hfinger,
 
Thank you for bringing this issue to our attention. We appreciate your patience and understand the frustration caused by the persistent Gnome Notification from Tomte.

We're pleased to inform you that the underlying bug in the distribution has been identified and fixed. To resolve this issue on your end, we recommend checking for updates to ensure you have the latest software version. After updating, please restart your system to apply the fixes.

If, after updating, the issue persists, we recommend reaching out to our support team through the TUXEDO Control Center application. They will be able to provide further assistance and address any lingering concerns you may have.

We apologize for any inconvenience this has caused and appreciate your understanding.

Best regards,
M. Arnold
