### ISSUE TITLE
tuxedo-tomte.service hangs at system start 

### ISSUE THREAD

**Issue by ykarrde** [tuxedocomputers/tuxedo-tomte#26]
I have here a TUXEDO Gemini 17 - Gen2 laptop and some problems related to tomte.

If I open the Tuxedo control center and go to Settings Tomte I just get a error message.
<img width="1003" alt="Screenshot_20230806_075831" src="https://github.com/tuxedocomputers/tuxedo-tomte/assets/6797383/7febc953-5b4c-4e8b-94a3-a0afcb3044e6">

so i checked the service:

```
> service tuxedo-tomte status
●  tuxedo-tomte.service - Tomte-daemon, finishes tasks that could not be accomplished before
     Loaded: loaded (/lib/systemd/system/tuxedo-tomte.service; static)
     Active: activating (start) since Fri 2023-08-04 09:43:07 CEST; 1min 57s ago
TriggeredBy: ● tuxedo-tomte.timer
   Main PID: 1261 (tuxedo-tomte)
      Tasks: 16 (limit: 76534)
     Memory: 109.6M
        CPU: 1.544s
     CGroup: /system.slice/tuxedo-tomte.service
             ├─1261 /usr/bin/perl -w /usr/bin/tuxedo-tomte configure all
             ├─1794 apt-get update
             ├─1798 /usr/lib/apt/methods/https
             ├─1799 /usr/lib/apt/methods/https
             ├─1800 /usr/lib/apt/methods/https
             ├─1801 /usr/lib/apt/methods/https
             ├─1802 /usr/lib/apt/methods/https
             ├─1803 /usr/lib/apt/methods/https
             ├─1804 /usr/lib/apt/methods/https
             ├─1805 /usr/lib/apt/methods/https
             ├─1806 /usr/lib/apt/methods/https
             ├─1807 /usr/lib/apt/methods/mirror+file
             ├─1808 /usr/lib/apt/methods/https
             ├─1809 /usr/lib/apt/methods/https
             ├─1811 /usr/lib/apt/methods/file
             └─2653 /usr/lib/apt/methods/gpgv

Aug 04 09:43:07 tux-158764 systemd[1]: Starting Tomte-daemon, finishes tasks that could not be accomplished before...
Aug 04 09:43:18 tux-158764 tuxedo-tomte[1261]: no network found!! some fixes might not be applied correctly
Aug 04 09:43:18 tux-158764 tuxedo-tomte[1261]: systemctlCmd: systemd-run --on-active="30sec" tuxedo-tomte configure all >/dev/null 2>&1
```
when i stop the service (_sudo service tuxedo-tomte stop_) and start it myself (_sudo service tuxedo-tomte start_) everything runs fine:

```
> service tuxedo-tomte status
○ tuxedo-tomte.service - Tomte-daemon, finishes tasks that could not be accomplished before
     Loaded: loaded (/lib/systemd/system/tuxedo-tomte.service; static)
     Active: inactive (dead) since Fri 2023-08-04 09:47:33 CEST; 4s ago
TriggeredBy: ● tuxedo-tomte.timer
    Process: 5164 ExecStart=/usr/bin/tuxedo-tomte configure all (code=exited, status=0/SUCCESS)
   Main PID: 5164 (code=exited, status=0/SUCCESS)
        CPU: 5.951s

Aug 04 09:47:33 tux-158764 tuxedo-tomte[5164]: - tuxedo-repos: Prerequisite! Adds the TUXEDO repositories
Aug 04 09:47:33 tux-158764 tuxedo-tomte[5164]: - tuxedo-mirrors: Adds TUXEDO maintained Ubuntu repositories
Aug 04 09:47:33 tux-158764 tuxedo-tomte[5164]: - cracklib-runtime: Builds password dictionary databases
Aug 04 09:47:33 tux-158764 tuxedo-tomte[5164]: - tuxedo-keyboard: Keyboard & keyboard backlight driver for TUXEDO notebooks
Aug 04 09:47:33 tux-158764 tuxedo-tomte[5164]: - linux-tuxedo-22.04: Required kernel version linux-tuxedo-22.04
Aug 04 09:47:33 tux-158764 tuxedo-tomte[5164]: - tuxedo-dgpu-run: commandline tool and KDE context menu entries to run programms on dGPU while>
Aug 04 09:47:33 tux-158764 tuxedo-tomte[5164]: Nothing to do in post configuration
Aug 04 09:47:33 tux-158764 systemd[1]: tuxedo-tomte.service: Deactivated successfully.
Aug 04 09:47:33 tux-158764 systemd[1]: Finished Tomte-daemon, finishes tasks that could not be accomplished before.
Aug 04 09:47:33 tux-158764 systemd[1]: tuxedo-tomte.service: Consumed 5.951s CPU time.
```

Finished in a few seconds. 
While the first auto started one was stuck with "no network found"? My Wi-Fi network was probably not up so early. 

Now i can access Tomte via the control center (until the next system restart).

**Edit**: forgot to mention I am using Tuxedo OS (up to date) tuxedo-tomte 2.11.0
**Edit2**: Added image of the error messages, system at that point already running with a working internet connection for more than 10 Minutes. Manually restarting the service resolved the issue, until i shutdown my Laptop and start it again. 

**Edit3** Today, 3 days later, I discovered that even KDE discover (what a Pun) throws an error while that tomte service is stuck:
_E: Sperre /var/lib/apt/lists/lock konnte nicht erlangt werden. Sie wird von Prozess 1870 (apt-get) gehalten.
W: Beachten Sie, dass das Entfernen der Sperrdatei keine Lösung ist und Ihr System beschädigen kann.
E: Das Verzeichnis /var/lib/apt/lists/ kann nicht gesperrt werden._
And the system can probably not even search for Updates that way(?).
That is really bad.

**Comment by ykarrde** [comment]
to continue this journey:
After (sudo) apt-get update (which basically was Process 1870 above) ran without any problems after stopping the tuxedo-tomte service. To check if the "no network found" with two exclamation Marks output is more likely the issue I changed the start time from 3 seconds to 1 Minute after boot. Which should give me enough time to login and establish a Wi-Fi Internet connection. At least most of the times, sometimes i tend to turn on the laptop and than "quickly" do something else until I login.
Long story short:
Rebooted Laptop, logged in and established internet connection.
Waited a short time and then checked the status of the tuxedo-tomte service, everything ran without errors, KDE Discover does not complain and tomte is accessible from the control center settings.

But why run apt-get update when there clearly is no network detected in the first place?
expected behavior would be:
Do not even search for an (online) Update if there is no network.  

**Edit 11.08.2023**
Update to 2.12.2 didn't fix the issue.
I know because the Update reverted my modified timer setting.
Re-reverted that back for now, despite being a far from perfect Workaround.

**Comment by ykarrde** [comment]
Since one of the last updates i get additionally 1001 apt error messages because Tomte decided to add Packages sources again, example:

**Ziel Packages (main/binary-amd64/Packages) ist mehrfach konfiguriert in /etc/apt/sources.list.d/tuxedo-computers.list:1 und /etc/apt/sources.list.d/tuxedo-computers.list:7**

And in the ".list" file(s) itself: "**# Added by TUXEDO Tomte ...**"

**Comment by tuxedo-ma** [comment]
Hi @ykarrde ,

Thank you for reaching out to us regarding the issues you're experiencing with the TUXEDO Tomte service on your Gemini 17 - Gen2 laptop. We appreciate the detailed information you provided about the error messages and your troubleshooting steps.

It appears that there are two main issues at hand:

1. The "no network found" error during the automatic start of the tuxedo-tomte service.
2. The addition of duplicate package sources, leading to apt errors.

Let's address each of these:

### Issue 1: "no network found" during automatic start

It seems that the tuxedo-tomte service is starting before your Wi-Fi network is fully established, resulting in the "no network found" error. We are in discussions about improving the network-check capabilities of Tomte. Your workaround of manually stopping and starting the service after boot seems to resolve the issue for you.

To prevent this from happening, you adjusted the timer setting to delay the start of the service. However, this is not a perfect solution, and we understand that it's not ideal for you. Please contact our support by the Tuxedo Control Center.

### Issue 2: Duplicate Package Source Errors

It seems that Tomte is repeatedly adding package sources, leading to duplicate configurations. This behavior is unexpected and may be causing the apt errors you mentioned.

This bug should've been fixed since you wrote the comment. If it persists please contact the support by the Tuxedo Control Center so we can get it fixed.

We understand the frustration these issues may be causing, and we appreciate your patience and detailed troubleshooting. If you have any further questions or if there's anything else we can assist you with, feel free to let us know.

Best regards,
M. Arnold
