### ISSUE TITLE
"Tuxedo Tomte is installing fixes" never disappears

### ISSUE THREAD

**Issue by Mailaender** [tuxedocomputers/tuxedo-tomte#35]
You can only guess that it is done from the noise of the fans. It says "don't turn off your computer" which makes this problematic.

**Comment by Emohr-Tuxedo** [comment]
Which Ubuntu flavour are you using? Which Tomte version? (tomte versions)
It is possible that Tomte has some problem installing a module, could be because of a broken package management, missing dependencies, etc.
Maybe you could post the lines from the last time Tomte was executed from the logfile (/var/log/tomte/tomte.log)?

**Comment by Mailaender** [comment]
I am using Tuxedo OS. It took very long and then it showed a message that it failed and I should restart and try again next time. I just didn't expect it to work several hours long.
